import os
import sys
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# Ensure the root directory is in the path so we can import from `agent/graph.py`
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Load environment variables FIRST before importing any LangChain modules that require them
load_dotenv()

from agent.engine import app as agent_app
from langchain_core.messages import HumanMessage

app = FastAPI(
    title="E2E Agent AI Backend",
    description="Commercial REST API for the LangGraph E2E Agent.",
    version="1.0.0"
)

# Enable CORS for the future Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, restrict this to the specific frontend domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----------------- Schemas -----------------
class ChatRequest(BaseModel):
    message: str
    # In Phase 3, we will add tenant_id or user_id here for Multi-Tenancy

class ChatResponse(BaseModel):
    reply: str
    status: str = "success"

# ----------------- Routes -----------------
@app.get("/health")
def health_check():
    return {"status": "ok", "message": "FastAPI Agent Gateway is running."}

@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Primary endpoint for the frontend to interact with the LangGraph Agent.
    """
    try:
        inputs = {"messages": [HumanMessage(content=request.message)]}
        # Invoke the stateful LangGraph agent
        response_state = agent_app.invoke(inputs)
        
        # Extract the final message content generated by the LLM
        final_reply = response_state["messages"][-1].content
        
        return ChatResponse(reply=final_reply)
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent Error: {str(e)}")

# To run locally: uvicorn api.main:app --reload --port 8000
